export const EQUIPMENT_LIST_REQUEST = 'EQUIPMENT_LIST_REQUEST';
export const EQUIPMENT_LIST_SUCCESS = 'EQUIPMENT_LIST_SUCCESS';
export const EQUIPMENT_LIST_FAIL = 'EQUIPMENT_LIST_FAIL';

export const EQUIPMENT_CREATE_REQUEST = 'EQUIPMENT_CREATE_REQUEST';
export const EQUIPMENT_CREATE_SUCCESS = 'EQUIPMENT_CREATE_SUCCESS';
export const EQUIPMENT_CREATE_FAIL = 'EQUIPMENT_CREATE_FAIL';
